//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Odds_Grabber___dafa888.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ______odds_issend_01 {
            get {
                return ((bool)(this["______odds_issend_01"]));
            }
            set {
                this["______odds_issend_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ______odds_issend_02 {
            get {
                return ((bool)(this["______odds_issend_02"]));
            }
            set {
                this["______odds_issend_02"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ______odds_iswaiting_01 {
            get {
                return ((bool)(this["______odds_iswaiting_01"]));
            }
            set {
                this["______odds_iswaiting_01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ______odds_iswaiting_02 {
            get {
                return ((bool)(this["______odds_iswaiting_02"]));
            }
            set {
                this["______odds_iswaiting_02"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"0-0.5|0.25
0.5-1|0.75
1-1.5|1.25
1.5-2|1.75
2-2.5|2.25
2.5-3|2.75
3-3.5|3.25
3.5-4|3.75
4-4.5|4.25
4.5-5|4.75
5-5.5|5.25
5.5-6|5.75
6-6.5|6.25
6.5-7|6.75
7-7.5|7.25
7.5-8|7.75
8-8.5|8.25
8.5-9|8.75
9-9.5|9.25
9.5-10|9.75
10-10.5|10.25
10.5-11|10.75
11-11.5|11.25
11.5-12|11.75")]
        public string ______odds {
            get {
                return ((string)(this["______odds"]));
            }
            set {
                this["______odds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("02813ed4183fb4f1e73d7a758695418d")]
        public string ______hash {
            get {
                return ((string)(this["______hash"]));
            }
            set {
                this["______hash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ______is_send_telegram {
            get {
                return ((bool)(this["______is_send_telegram"]));
            }
            set {
                this["______is_send_telegram"] = value;
            }
        }
    }
}
